function OnEvent(event, arg)
  if (event == "MOUSE_BUTTON_PRESSED" and arg == 8) then
    LDT()
  end
end
function LDT()
  MoveMouseRelative(1300, 1000)
  Sleep(10)
  PressKey("lctrl")
  Sleep(20)
  PressAndReleaseKey("spacebar")
  Sleep(10)
  PressAndReleaseMouseButton(1)
  Sleep(15)
  PressAndReleaseMouseButton(3)
  Sleep(30)
  MoveMouseRelative(-1300, -1000)
  ReleaseKey("lctrl")
end
function LDTC()
  MoveMouseRelative(800, 1000)
  Sleep(20)
  PressKey("lctrl")
  Sleep(10)
  PressAndReleaseKey("spacebar")
  Sleep(20)
  PressAndReleaseMouseButton(1)
  Sleep(20)
  PressAndReleaseMouseButton(3)
  MoveMouseRelative(-800,-1000)
  ReleaseKey("lctrl")
end